import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";
import { fontUbuntu } from "@/config/fonts";

export const metadata: Metadata = {
  title: "molly's blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fontUbuntu.className, "tracking-wide")}>
        <Providers>
          <div className="dark:bg-[#0b0f11] overflow-y-auto scrollbar-hide min-h-screen">
            <main className="container mx-auto max-w-5xl pt-10 pb-[25px] md:pt-16 flex flex-col">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
